### ISSUE TITLE
BUG: Crash

### ISSUE THREAD

**Issue by jeferson-santos** [opentibiabr/otservbr-global-archived#2387]
Thread 1 "otbr" received signal SIGSEGV, Segmentation fault.
2021-02-09 23:55:46 -  0x00007fffae7fbd38 in ?? ()
2021-02-09 23:55:46 -
2021-02-09 23:55:46 -  Thread 4 (Thread 0x7ffff4c93700 (LWP 7176)):
2021-02-09 23:55:46 -  #0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x5555558b29ac <g_databaseTasks+140>) at ../sysdeps/nptl/futex-internal.h:183
2021-02-09 23:55:46 -          __ret = -512
2021-02-09 23:55:46 -          oldtype = 0
2021-02-09 23:55:46 -          err = <optimized out>
2021-02-09 23:55:46 -          oldtype = <optimized out>
2021-02-09 23:55:46 -          err = <optimized out>
2021-02-09 23:55:46 -          __ret = <optimized out>
2021-02-09 23:55:46 -          resultvar = <optimized out>
2021-02-09 23:55:46 -          __arg4 = <optimized out>
2021-02-09 23:55:46 -          __arg3 = <optimized out>
2021-02-09 23:55:46 -          __arg2 = <optimized out>
2021-02-09 23:55:46 -          __arg1 = <optimized out>
2021-02-09 23:55:46 -          _a4 = <optimized out>
2021-02-09 23:55:46 -          _a3 = <optimized out>
2021-02-09 23:55:46 -          _a2 = <optimized out>
2021-02-09 23:55:46 -          _a1 = <optimized out>
2021-02-09 23:55:46 -  #1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x5555558b2958 <g_databaseTasks+56>, cond=0x5555558b2980 <g_databaseTasks+96>) at pthread_cond_wait.c:508
2021-02-09 23:55:46 -          spin = 0
2021-02-09 23:55:46 -          buffer = {__routine = 0x7ffff71fe050 <__condvar_cleanup_waiting>, __arg = 0x7ffff4c92b50, __canceltype = 2002740332, __prev = 0x0}
2021-02-09 23:55:46 -          cbuffer = {wseq = 7, cond = 0x5555558b2980 <g_databaseTasks+96>, mutex = 0x5555558b2958 <g_databaseTasks+56>, private = 0}
2021-02-09 23:55:46 -          err = <optimized out>
2021-02-09 23:55:46 -          g = 1
2021-02-09 23:55:46 -          flags = <optimized out>
2021-02-09 23:55:46 -          g1_start = <optimized out>
2021-02-09 23:55:46 -          signals = <optimized out>
2021-02-09 23:55:46 -          result = 0
2021-02-09 23:55:46 -          wseq = 7
2021-02-09 23:55:46 -          seq = 3
2021-02-09 23:55:46 -          private = <optimized out>
2021-02-09 23:55:46 -          maxspin = <optimized out>
2021-02-09 23:55:46 -          err = <optimized out>
2021-02-09 23:55:46 -          result = <optimized out>
2021-02-09 23:55:46 -          wseq = <optimized out>
2021-02-09 23:55:46 -          g = <optimized out>
2021-02-09 23:55:46 -          seq = <optimized out>
2021-02-09 23:55:46 -          flags = <optimized out>
2021-02-09 23:55:46 -          private = <optimized out>
2021-02-09 23:55:46 -          signals = <optimized out>
2021-02-09 23:55:46 -          g1_start = <optimized out>
2021-02-09 23:55:46 -          spin = <optimized out>
2021-02-09 23:55:46 -          buffer = <optimized out>
2021-02-09 23:55:46 -          cbuffer = <optimized out>
2021-02-09 23:55:46 -          s = <optimized out>
2021-02-09 23:55:46 -  #2  __pthread_cond_wait (cond=0x5555558b2980 <g_databaseTasks+96>, mutex=0x5555558b2958 <g_databaseTasks+56>) at pthread_cond_wait.c:638
2021-02-09 23:55:46 -  No locals.
2021-02-09 23:55:46 -  #3  0x00007ffff7016e50 in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /lib/x86_64-linux-gnu/libstdc++.so.6
2021-02-09 23:55:46 -  No symbol table info available.
2021-02-09 23:55:46 -  #4  0x0000555555801ddc in DatabaseTasks::threadMain() ()
2021-02-09 23:55:46 -  No symbol table info available.
2021-02-09 23:55:46 -  #5  0x00007ffff701cd84 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
2021-02-09 23:55:46 -  No symbol table info available.
2021-02-09 23:55:46 -  #6  0x00007ffff71f7609 in start_thread (arg=<optimized out>) at pthread_create.c:477
2021-02-09 23:55:46 -          ret = <optimized out>
2021-02-09 23:55:46 -          pd = <optimized out>
2021-02-09 23:55:46 -          unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737300215552, 1355640335819446288, 140737317078030, 140737317078031, 140737317078032, 140737300213056, -1355625124682426352, -1355621364738320368}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
2021-02-09 23:55:46 -          not_first_call = 0
2021-02-09 23:55:46 -  #7  0x00007ffff7ef1293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
2021-02-09 23:55:46 -  No locals.
2021-02-09 23:55:46 -
2021-02-09 23:55:46 -  Thread 3 (Thread 0x7ffff54a8700 (LWP 7175)):
2021-02-09 23:55:46 -  #0  futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7ffff54a7c00, clockid=<optimized out>, expected=0, futex_word=0x5555558b2868 <g_scheduler+104>) at ../sysdeps/nptl/futex-internal.h:320
2021-02-09 23:55:46 -          __ret = -110
2021-02-09 23:55:46 -          clockbit = <optimized out>
2021-02-09 23:55:46 -          op = <optimized out>
2021-02-09 23:55:46 -          __ret = <optimized out>
2021-02-09 23:55:46 -          oldtype = 0
2021-02-09 23:55:46 -          err = <optimized out>
2021-02-09 23:55:46 -          oldtype = <optimized out>
2021-02-09 23:55:46 -          err = <optimized out>
2021-02-09 23:55:46 -          __ret = <optimized out>
2021-02-09 23:55:46 -          clockbit = <optimized out>
2021-02-09 23:55:46 -          op = <optimized out>
2021-02-09 23:55:46 -          __ret = <optimized out>
2021-02-09 23:55:46 -          resultvar = <optimized out>
2021-02-09 23:55:46 -          __arg6 = <optimized out>
2021-02-09 23:55:46 -          __arg5 = <optimized out>
2021-02-09 23:55:46 -          __arg4 = <optimized out>
2021-02-09 23:55:46 -          __arg3 = <optimized out>
2021-02-09 23:55:46 -          __arg2 = <optimized out>
2021-02-09 23:55:46 -          __arg1 = <optimized out>
2021-02-09 23:55:46 -          _a6 = <optimized out>
2021-02-09 23:55:46 -          _a5 = <optimized out>
2021-02-09 23:55:46 -          _a4 = <optimized out>
2021-02-09 23:55:46 -          _a3 = <optimized out>
2021-02-09 23:55:46 -          _a2 = <optimized out>
2021-02-09 23:55:46 -          _a1 = <optimized out>
2021-02-09 23:55:46 -  #1  __pthread_cond_wait_common (abstime=0x7ffff54a7c00, clockid=<optimized out>, mutex=0x5555558b2818 <g_scheduler+24>, cond=0x5555558b2840 <g_scheduler+64>) at pthread_cond_wait.c:520
2021-02-09 23:55:46 -          spin = 0
2021-02-09 23:55:46 -          buffer = {__routine = 0x7ffff71fe050 <__condvar_cleanup_waiting>, __arg = 0x7ffff54a7b70, __canceltype = 1435424480, __prev = 0x0}
2021-02-09 23:55:46 -          cbuffer = {wseq = 2715990, cond = 0x5555558b2840 <g_scheduler+64>, mutex = 0x5555558b2818 <g_scheduler+24>, private = 0}
2021-02-09 23:55:46 -          err = <optimized out>
2021-02-09 23:55:46 -          g = 0
2021-02-09 23:55:46 -          flags = <optimized out>
2021-02-09 23:55:46 -          g1_start = <optimized out>
2021-02-09 23:55:46 -          maxspin = 0
2021-02-09 23:55:46 -          signals = <optimized out>
2021-02-09 23:55:46 -          result = 0
2021-02-09 23:55:46 -          wseq = 2715990
2021-02-09 23:55:46 -          seq = 1357995
2021-02-09 23:55:46 -          private = <optimized out>
2021-02-09 23:55:46 -          maxspin = <optimized out>
2021-02-09 23:55:46 -          err = <optimized out>
2021-02-09 23:55:46 -          result = <optimized out>
2021-02-09 23:55:46 -          wseq = <optimized out>
2021-02-09 23:55:46 -          g = <optimized out>
2021-02-09 23:55:46 -          seq = <optimized out>
2021-02-09 23:55:46 -          flags = <optimized out>
2021-02-09 23:55:46 -          private = <optimized out>
2021-02-09 23:55:46 -          signals = <optimized out>
2021-02-09 23:55:46 -          g1_start = <optimized out>
2021-02-09 23:55:46 -          spin = <optimized out>
2021-02-09 23:55:46 -          buffer = <optimized out>
2021-02-09 23:55:46 -          cbuffer = <optimized out>
2021-02-09 23:55:46 -          s = <optimized out>
2021-02-09 23:55:46 -  #2  __pthread_cond_timedwait (cond=0x5555558b2840 <g_scheduler+64>, mutex=0x5555558b2818 <g_scheduler+24>, abstime=0x7ffff54a7c00) at pthread_cond_wait.c:656
2021-02-09 23:55:46 -          flags = <optimized out>
2021-02-09 23:55:46 -          clockid = <optimized out>
2021-02-09 23:55:46 -  #3  0x00005555556a5436 in Scheduler::threadMain() ()
2021-02-09 23:55:46 -  No symbol table info available.
2021-02-09 23:55:46 -  #4  0x00007ffff701cd84 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
2021-02-09 23:55:46 -  No symbol table info available.
2021-02-09 23:55:46 -  #5  0x00007ffff71f7609 in start_thread (arg=<optimized out>) at pthread_create.c:477
2021-02-09 23:55:46 -          ret = <optimized out>
2021-02-09 23:55:46 -          pd = <optimized out>
2021-02-09 23:55:46 -          unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737308690176, 1355640335819446288, 140737488347630, 140737488347631, 140737488347632, 140737308687680, -1355626201108604912, -1355621364738320368}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
2021-02-09 23:55:46 -          not_first_call = 0
2021-02-09 23:55:46 -  #6  0x00007ffff7ef1293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
2021-02-09 23:55:46 -  No locals.
2021-02-09 23:55:46 -
2021-02-09 23:55:46 -  Thread 2 (Thread 0x7ffff5ca9700 (LWP 7174)):
2021-02-09 23:55:46 -  #0  0x00005555557d97db in std::_Function_handler<void (), std::_Bind<void (Game::*(Game*, unsigned long))(unsigned long)> >::_M_invoke(std::_Any_data const&) ()
2021-02-09 23:55:46 -  No symbol table info available.
2021-02-09 23:55:46 -  #1  0x000055555568c1c0 in Dispatcher::threadMain() ()
2021-02-09 23:55:46 -  No symbol table info available.
2021-02-09 23:55:46 -  #2  0x00007ffff701cd84 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
2021-02-09 23:55:46 -  No symbol table info available.
2021-02-09 23:55:46 -  #3  0x00007ffff71f7609 in start_thread (arg=<optimized out>) at pthread_create.c:477
2021-02-09 23:55:46 -          ret = <optimized out>
2021-02-09 23:55:46 -          pd = <optimized out>
2021-02-09 23:55:46 -          unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737317082880, 1355640335819446288, 140737488347630, 140737488347631, 140737488347632, 140737317080384, -1355627301157103600, -1355621364738320368}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
2021-02-09 23:55:46 -          not_first_call = 0
2021-02-09 23:55:46 -  #4  0x00007ffff7ef1293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
2021-02-09 23:55:46 -  No locals.
2021-02-09 23:55:46 -
2021-02-09 23:55:46 -  Thread 1 (Thread 0x7ffff5caf9c0 (LWP 7170)):
2021-02-09 23:55:46 -  #0  0x00007fffae7fbd38 in ?? ()
2021-02-09 23:55:46 -  No symbol table info available.
2021-02-09 23:55:46 -  #1  0x00005555556e4d49 in Player::postRemoveNotification(Thing*, Cylinder const*, int, cylinderlink_t) ()
2021-02-09 23:55:46 -  No symbol table info available.
2021-02-09 23:55:46 -  #2  0x00005555555e3acf in Game::internalRemoveItem(Item*, int, bool, unsigned int) [clone .constprop.0] ()
2021-02-09 23:55:46 -  No symbol table info available.
2021-02-09 23:55:46 -  #3  0x00005555556deb64 in Player::stowContainer(Item*, unsigned int) ()
2021-02-09 23:55:46 -  No symbol table info available.
2021-02-09 23:55:46 -  #4  0x00005555556b39f5 in ProtocolGame::parseStashWithdraw(NetworkMessage&) ()
2021-02-09 23:55:46 -  No symbol table info available.
2021-02-09 23:55:46 -  #5  0x00005555556d9e61 in ProtocolGame::parsePacket(NetworkMessage&) ()
2021-02-09 23:55:46 -  No symbol table info available.
2021-02-09 23:55:46 -  #6  0x00005555556497ca in Connection::parsePacket(boost::system::error_code const&) ()
2021-02-09 23:55:46 -  No symbol table info available.
2021-02-09 23:55:46 -  #7  0x0000555555648899 in boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>, boost::asio::mutable_buffers_1, boost::asio::mutable_buffer const*, boost::asio::detail::transfer_all_t, std::_Bind<void (Connection::*(std::shared_ptr<Connection>, std::_Placeholder<1>))(boost::system::error_code const&)> >::operator()(boost::system::error_code const&, unsigned long, int) ()
2021-02-09 23:55:46 -  No symbol table info available.
2021-02-09 23:55:46 -  #8  0x0000555555641a2a in boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor>, boost::asio::mutable_buffers_1, boost::asio::mutable_buffer const*, boost::asio::detail::transfer_all_t, std::_Bind<void (Connection::*(std::shared_ptr<Connection>, std::_Placeholder<1>))(boost::system::error_code const&)> >, boost::asio::detail::io_object_executor<boost::asio::executor> >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) ()
2021-02-09 23:55:46 -  No symbol table info available.
2021-02-09 23:55:46 -  #9  0x000055555581a917 in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
2021-02-09 23:55:46 -  No symbol table info available.
2021-02-09 23:55:46 -  #10 0x00005555555d61f3 in main ()
2021-02-09 23:55:46 -  No symbol table info available.
2021-02-09 23:55:46 -  A debugging session is active.
2021-02-09 23:55:46 -
2021-02-09 23:55:46 -   Inferior 1 [process 7170] will be killed.

**Comment by phacUFPE** [comment]
O que tu tava fazendo ou ia fazer no momento que crashou ?

**Comment by jeferson-santos** [comment]
Vou verificar as ações feitas, estou jogando com uns amigos, avisei eles
que se crashar novamente é pra me informar.

Em ter, 9 de fev de 2021 9:11 PM, Pedro Cruz <notifications@github.com
escreveu:

**Comment by marcosvf132** [comment]
Do you have the updated repo? There was a crash related to the supply stash (just like yours) but it was fixed on the PR #2359

**Comment by jeferson-santos** [comment]
Yes, I just updated, tested the erros that were correct and are really
working, but this error started to appear

Em ter., 9 de fev. de 2021 às 21:34, Marcos <notifications@github.com>
escreveu:
