### ISSUE TITLE
BUG: Crash server

### ISSUE THREAD

**Issue by methx** [opentibiabr/otservbr-global-archived#2401]
I have the server up to date, I don't understand why this happened, Does anyone know what the reason may be?

2021-02-12 20:22:21 -  Thread 2 "tfs" received signal SIGSEGV, Segmentation fault.
2021-02-12 20:22:21 -  [Switching to Thread 0x7fffef924700 (LWP 28146)]
2021-02-12 20:22:21 -  0x000055555572312c in Item::isRemoved() const [clone .lto_priv.1225] ()
2021-02-12 20:22:21 -  
2021-02-12 20:22:21 -  Thread 4 (Thread 0x7fffee710700 (LWP 28148)):
2021-02-12 20:22:21 -  #0  0x00007ffff61b3ad3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x555555a406ac <g_databaseTasks+140>) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
2021-02-12 20:22:21 -          __ret = -512
2021-02-12 20:22:21 -          oldtype = 0
2021-02-12 20:22:21 -          err = <optimized out>
2021-02-12 20:22:21 -          oldtype = <optimized out>
2021-02-12 20:22:21 -          err = <optimized out>
2021-02-12 20:22:21 -          __ret = <optimized out>
2021-02-12 20:22:21 -          resultvar = <optimized out>
2021-02-12 20:22:21 -          __arg4 = <optimized out>
2021-02-12 20:22:21 -          __arg3 = <optimized out>
2021-02-12 20:22:21 -          __arg2 = <optimized out>
2021-02-12 20:22:21 -          __arg1 = <optimized out>
2021-02-12 20:22:21 -          _a4 = <optimized out>
2021-02-12 20:22:21 -          _a3 = <optimized out>
2021-02-12 20:22:21 -          _a2 = <optimized out>
2021-02-12 20:22:21 -          _a1 = <optimized out>
2021-02-12 20:22:21 -  #1  __pthread_cond_wait_common (abstime=0x0, mutex=0x555555a40658 <g_databaseTasks+56>, cond=0x555555a40680 <g_databaseTasks+96>) at pthread_cond_wait.c:502
2021-02-12 20:22:21 -          spin = 0
2021-02-12 20:22:21 -          buffer = {__routine = 0x7ffff61b3770 <__condvar_cleanup_waiting>, __arg = 0x7fffee70fd00, __canceltype = -671088608, __prev = 0x0}
2021-02-12 20:22:21 -          cbuffer = {wseq = 71, cond = 0x555555a40680 <g_databaseTasks+96>, mutex = 0x555555a40658 <g_databaseTasks+56>, private = 0}
2021-02-12 20:22:21 -          rt = <optimized out>
2021-02-12 20:22:21 -          err = <optimized out>
2021-02-12 20:22:21 -          g = 1
2021-02-12 20:22:21 -          flags = <optimized out>
2021-02-12 20:22:21 -          g1_start = <optimized out>
2021-02-12 20:22:21 -          signals = <optimized out>
2021-02-12 20:22:21 -          result = 0
2021-02-12 20:22:21 -          wseq = <optimized out>
2021-02-12 20:22:21 -          seq = 35
2021-02-12 20:22:21 -          private = <optimized out>
2021-02-12 20:22:21 -          maxspin = <optimized out>
2021-02-12 20:22:21 -          err = <optimized out>
2021-02-12 20:22:21 -          result = <optimized out>
2021-02-12 20:22:21 -          wseq = <optimized out>
2021-02-12 20:22:21 -          g = <optimized out>
2021-02-12 20:22:21 -          seq = <optimized out>
2021-02-12 20:22:21 -          flags = <optimized out>
2021-02-12 20:22:21 -          private = <optimized out>
2021-02-12 20:22:21 -          signals = <optimized out>
2021-02-12 20:22:21 -          g1_start = <optimized out>
2021-02-12 20:22:21 -          spin = <optimized out>
2021-02-12 20:22:21 -          buffer = <optimized out>
2021-02-12 20:22:21 -          cbuffer = <optimized out>
2021-02-12 20:22:21 -          rt = <optimized out>
2021-02-12 20:22:21 -          s = <optimized out>
2021-02-12 20:22:21 -  #2  __pthread_cond_wait (cond=0x555555a40680 <g_databaseTasks+96>, mutex=0x555555a40658 <g_databaseTasks+56>) at pthread_cond_wait.c:655
2021-02-12 20:22:21 -  No locals.
2021-02-12 20:22:21 -  #3  0x00007ffff5a238bc in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
2021-02-12 20:22:21 -  No symbol table info available.
2021-02-12 20:22:21 -  #4  0x000055555572eb4e in DatabaseTasks::threadMain() ()
2021-02-12 20:22:21 -  No symbol table info available.
2021-02-12 20:22:21 -  #5  0x00007ffff5a296df in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
2021-02-12 20:22:21 -  No symbol table info available.
2021-02-12 20:22:21 -  #6  0x00007ffff61ad6db in start_thread (arg=0x7fffee710700) at pthread_create.c:463
2021-02-12 20:22:21 -          pd = 0x7fffee710700
2021-02-12 20:22:21 -          now = <optimized out>
2021-02-12 20:22:21 -          unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737193772800, 3988056587605277011, 140737193770880, 0, 140737085998912, 140737212721760, -3988024641668089517, -3988077779821627053}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
2021-02-12 20:22:21 -          not_first_call = <optimized out>
2021-02-12 20:22:21 -  #7  0x00007ffff7b0371f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
2021-02-12 20:22:21 -  No locals.
2021-02-12 20:22:21 -  
2021-02-12 20:22:21 -  Thread 3 (Thread 0x7fffef123700 (LWP 28147)):
2021-02-12 20:22:21 -  #0  0x00007ffff61b4065 in futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7fffef122e40, expected=0, futex_word=0x555555a4056c <g_scheduler+108>) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
2021-02-12 20:22:21 -          __ret = -516
2021-02-12 20:22:21 -          oldtype = 0
2021-02-12 20:22:21 -          err = <optimized out>
2021-02-12 20:22:21 -          oldtype = <optimized out>
2021-02-12 20:22:21 -          err = <optimized out>
2021-02-12 20:22:21 -          __ret = <optimized out>
2021-02-12 20:22:21 -          resultvar = <optimized out>
2021-02-12 20:22:21 -          __arg6 = <optimized out>
2021-02-12 20:22:21 -          __arg5 = <optimized out>
2021-02-12 20:22:21 -          __arg4 = <optimized out>
2021-02-12 20:22:21 -          __arg3 = <optimized out>
2021-02-12 20:22:21 -          __arg2 = <optimized out>
2021-02-12 20:22:21 -          __arg1 = <optimized out>
2021-02-12 20:22:21 -          _a6 = <optimized out>
2021-02-12 20:22:21 -          _a5 = <optimized out>
2021-02-12 20:22:21 -          _a4 = <optimized out>
2021-02-12 20:22:21 -          _a3 = <optimized out>
2021-02-12 20:22:21 -          _a2 = <optimized out>
2021-02-12 20:22:21 -          _a1 = <optimized out>
2021-02-12 20:22:21 -  #1  __pthread_cond_wait_common (abstime=0x7fffef122e40, mutex=0x555555a40518 <g_scheduler+24>, cond=0x555555a40540 <g_scheduler+64>) at pthread_cond_wait.c:539
2021-02-12 20:22:21 -          spin = 0
2021-02-12 20:22:21 -          buffer = {__routine = 0x7ffff61b3770 <__condvar_cleanup_waiting>, __arg = 0x7fffef122dc0, __canceltype = 1437033216, __prev = 0x0}
2021-02-12 20:22:21 -          cbuffer = {wseq = 122781645, cond = 0x555555a40540 <g_scheduler+64>, mutex = 0x555555a40518 <g_scheduler+24>, private = 0}
2021-02-12 20:22:21 -          err = <optimized out>
2021-02-12 20:22:21 -          g = 1
2021-02-12 20:22:21 -          flags = <optimized out>
2021-02-12 20:22:21 -          g1_start = <optimized out>
2021-02-12 20:22:21 -          maxspin = 0
2021-02-12 20:22:21 -          signals = <optimized out>
2021-02-12 20:22:21 -          result = 0
2021-02-12 20:22:21 -          wseq = <optimized out>
2021-02-12 20:22:21 -          seq = 61390822
2021-02-12 20:22:21 -          private = <optimized out>
2021-02-12 20:22:21 -          maxspin = <optimized out>
2021-02-12 20:22:21 -          err = <optimized out>
2021-02-12 20:22:21 -          result = <optimized out>
2021-02-12 20:22:21 -          wseq = <optimized out>
2021-02-12 20:22:21 -          g = <optimized out>
2021-02-12 20:22:21 -          seq = <optimized out>
2021-02-12 20:22:21 -          flags = <optimized out>
2021-02-12 20:22:21 -          private = <optimized out>
2021-02-12 20:22:21 -          signals = <optimized out>
2021-02-12 20:22:21 -          g1_start = <optimized out>
2021-02-12 20:22:21 -          spin = <optimized out>
2021-02-12 20:22:21 -          buffer = <optimized out>
2021-02-12 20:22:21 -          cbuffer = <optimized out>
2021-02-12 20:22:21 -          rt = <optimized out>
2021-02-12 20:22:21 -          s = <optimized out>
2021-02-12 20:22:21 -  #2  __pthread_cond_timedwait (cond=0x555555a40540 <g_scheduler+64>, mutex=0x555555a40518 <g_scheduler+24>, abstime=0x7fffef122e40) at pthread_cond_wait.c:667
2021-02-12 20:22:21 -  No locals.
2021-02-12 20:22:21 -  #3  0x000055555566f6a7 in Scheduler::threadMain() ()
2021-02-12 20:22:21 -  No symbol table info available.
2021-02-12 20:22:21 -  #4  0x00007ffff5a296df in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
2021-02-12 20:22:21 -  No symbol table info available.
2021-02-12 20:22:21 -  #5  0x00007ffff61ad6db in start_thread (arg=0x7fffef123700) at pthread_create.c:463
2021-02-12 20:22:21 -          pd = 0x7fffef123700
2021-02-12 20:22:21 -          now = <optimized out>
2021-02-12 20:22:21 -          unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737204336384, 3988056587605277011, 140737204334464, 0, 93824997617520, 140737488346160, -3988022740608190125, -3988077779821627053}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
2021-02-12 20:22:21 -          not_first_call = <optimized out>
2021-02-12 20:22:21 -  #6  0x00007ffff7b0371f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
2021-02-12 20:22:21 -  No locals.
2021-02-12 20:22:21 -  
2021-02-12 20:22:21 -  Thread 2 (Thread 0x7fffef924700 (LWP 28146)):
2021-02-12 20:22:21 -  #0  0x000055555572312c in Item::isRemoved() const [clone .lto_priv.1225] ()
2021-02-12 20:22:21 -  No symbol table info available.
2021-02-12 20:22:21 -  #1  0x0000555555754ede in Game::checkDecay() ()
2021-02-12 20:22:21 -  No symbol table info available.
2021-02-12 20:22:21 -  #2  0x00005555556afd8f in Dispatcher::threadMain() ()
2021-02-12 20:22:21 -  No symbol table info available.
2021-02-12 20:22:21 -  #3  0x00007ffff5a296df in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
2021-02-12 20:22:21 -  No symbol table info available.
2021-02-12 20:22:21 -  #4  0x00007ffff61ad6db in start_thread (arg=0x7fffef924700) at pthread_create.c:463
2021-02-12 20:22:21 -          pd = 0x7fffef924700
2021-02-12 20:22:21 -          now = <optimized out>
2021-02-12 20:22:21 -          unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737212729088, 3988056587605277011, 140737212727168, 0, 93824997617120, 140737488346160, -3988021641633433261, -3988077779821627053}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
2021-02-12 20:22:21 -          not_first_call = <optimized out>
2021-02-12 20:22:21 -  #5  0x00007ffff7b0371f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
2021-02-12 20:22:21 -  No locals.
2021-02-12 20:22:21 -  
2021-02-12 20:22:21 -  Thread 1 (Thread 0x7ffff7fd3780 (LWP 28142)):
2021-02-12 20:22:21 -  #0  0x00007ffff7b03a47 in epoll_wait (epfd=4, events=0x7fffffffde70, maxevents=128, timeout=-1) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
2021-02-12 20:22:21 -          resultvar = 18446744073709551612
2021-02-12 20:22:21 -          sc_cancel_oldtype = 0
2021-02-12 20:22:21 -          sc_ret = <optimized out>
2021-02-12 20:22:21 -  #1  0x000055555559be26 in main ()
2021-02-12 20:22:21 -  No symbol table info available.
2021-02-12 20:22:21 -  antirollback_config:8: Error in sourced command file:
2021-02-12 20:22:21 -  No symbol "saveServer" in current context.

**Comment by dudantas** [comment]
Resolved with the revert of the last commit.
