### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by methx** [opentibiabr/otservbr-global-archived#2447]
Does anyone know the reasons why this can happen?

2021-02-21 16:46:51 -  Thread 1 "tfs" received signal SIGSEGV, Segmentation fault.
2021-02-21 16:46:51 -  0x00005555556991b7 in Player::postRemoveNotification(Thing*, Cylinder const*, int, cylinderlink_t) ()
2021-02-21 16:46:51 -  
2021-02-21 16:46:51 -  Thread 4 (Thread 0x7fffee710700 (LWP 28830)):
2021-02-21 16:46:51 -  #0  0x00007ffff61b3ad3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x555555a406a8 <g_databaseTasks+136>) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
2021-02-21 16:46:51 -          __ret = -512
2021-02-21 16:46:51 -          oldtype = 0
2021-02-21 16:46:51 -          err = <optimized out>
2021-02-21 16:46:51 -          oldtype = <optimized out>
2021-02-21 16:46:51 -          err = <optimized out>
2021-02-21 16:46:51 -          __ret = <optimized out>
2021-02-21 16:46:51 -          resultvar = <optimized out>
2021-02-21 16:46:51 -          __arg4 = <optimized out>
2021-02-21 16:46:51 -          __arg3 = <optimized out>
2021-02-21 16:46:51 -          __arg2 = <optimized out>
2021-02-21 16:46:51 -          __arg1 = <optimized out>
2021-02-21 16:46:51 -          _a4 = <optimized out>
2021-02-21 16:46:51 -          _a3 = <optimized out>
2021-02-21 16:46:51 -          _a2 = <optimized out>
2021-02-21 16:46:51 -          _a1 = <optimized out>
2021-02-21 16:46:51 -  #1  __pthread_cond_wait_common (abstime=0x0, mutex=0x555555a40658 <g_databaseTasks+56>, cond=0x555555a40680 <g_databaseTasks+96>) at pthread_cond_wait.c:502
2021-02-21 16:46:51 -          spin = 0
2021-02-21 16:46:51 -          buffer = {__routine = 0x7ffff61b3770 <__condvar_cleanup_waiting>, __arg = 0x7fffee70fd00, __canceltype = -671088608, __prev = 0x0}
2021-02-21 16:46:51 -          cbuffer = {wseq = 64, cond = 0x555555a40680 <g_databaseTasks+96>, mutex = 0x555555a40658 <g_databaseTasks+56>, private = 0}
2021-02-21 16:46:51 -          rt = <optimized out>
2021-02-21 16:46:51 -          err = <optimized out>
2021-02-21 16:46:51 -          g = 0
2021-02-21 16:46:51 -          flags = <optimized out>
2021-02-21 16:46:51 -          g1_start = <optimized out>
2021-02-21 16:46:51 -          signals = <optimized out>
2021-02-21 16:46:51 -          result = 0
2021-02-21 16:46:51 -          wseq = <optimized out>
2021-02-21 16:46:51 -          seq = 32
2021-02-21 16:46:51 -          private = <optimized out>
2021-02-21 16:46:51 -          maxspin = <optimized out>
2021-02-21 16:46:51 -          err = <optimized out>
2021-02-21 16:46:51 -          result = <optimized out>
2021-02-21 16:46:51 -          wseq = <optimized out>
2021-02-21 16:46:51 -          g = <optimized out>
2021-02-21 16:46:51 -          seq = <optimized out>
2021-02-21 16:46:51 -          flags = <optimized out>
2021-02-21 16:46:51 -          private = <optimized out>
2021-02-21 16:46:51 -          signals = <optimized out>
2021-02-21 16:46:51 -          g1_start = <optimized out>
2021-02-21 16:46:51 -          spin = <optimized out>
2021-02-21 16:46:51 -          buffer = <optimized out>
2021-02-21 16:46:51 -          cbuffer = <optimized out>
2021-02-21 16:46:51 -          rt = <optimized out>
2021-02-21 16:46:51 -          s = <optimized out>
2021-02-21 16:46:51 -  #2  __pthread_cond_wait (cond=0x555555a40680 <g_databaseTasks+96>, mutex=0x555555a40658 <g_databaseTasks+56>) at pthread_cond_wait.c:655
2021-02-21 16:46:51 -  No locals.
2021-02-21 16:46:51 -  #3  0x00007ffff5a238bc in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
2021-02-21 16:46:51 -  No symbol table info available.
2021-02-21 16:46:51 -  #4  0x000055555572ec5e in DatabaseTasks::threadMain() ()
2021-02-21 16:46:51 -  No symbol table info available.
2021-02-21 16:46:51 -  #5  0x00007ffff5a296df in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
2021-02-21 16:46:51 -  No symbol table info available.
2021-02-21 16:46:51 -  #6  0x00007ffff61ad6db in start_thread (arg=0x7fffee710700) at pthread_create.c:463
2021-02-21 16:46:51 -          pd = 0x7fffee710700
2021-02-21 16:46:51 -          now = <optimized out>
2021-02-21 16:46:51 -          unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737193772800, -2174702167556859638, 140737193770880, 0, 140737085963664, 140737212721760, 2174740573179631882, 2174688672002365706}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
2021-02-21 16:46:51 -          not_first_call = <optimized out>
2021-02-21 16:46:51 -  #7  0x00007ffff7b0371f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
2021-02-21 16:46:51 -  No locals.
2021-02-21 16:46:51 -  
2021-02-21 16:46:51 -  Thread 3 (Thread 0x7fffef123700 (LWP 28829)):
2021-02-21 16:46:51 -  #0  0x00007ffff61b4065 in futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7fffef122e40, expected=0, futex_word=0x555555a40568 <g_scheduler+104>) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
2021-02-21 16:46:51 -          __ret = -516
2021-02-21 16:46:51 -          oldtype = 0
2021-02-21 16:46:51 -          err = <optimized out>
2021-02-21 16:46:51 -          oldtype = <optimized out>
2021-02-21 16:46:51 -          err = <optimized out>
2021-02-21 16:46:51 -          __ret = <optimized out>
2021-02-21 16:46:51 -          resultvar = <optimized out>
2021-02-21 16:46:51 -          __arg6 = <optimized out>
2021-02-21 16:46:51 -          __arg5 = <optimized out>
2021-02-21 16:46:51 -          __arg4 = <optimized out>
2021-02-21 16:46:51 -          __arg3 = <optimized out>
2021-02-21 16:46:51 -          __arg2 = <optimized out>
2021-02-21 16:46:51 -          __arg1 = <optimized out>
2021-02-21 16:46:51 -          _a6 = <optimized out>
2021-02-21 16:46:51 -          _a5 = <optimized out>
2021-02-21 16:46:51 -          _a4 = <optimized out>
2021-02-21 16:46:51 -          _a3 = <optimized out>
2021-02-21 16:46:51 -          _a2 = <optimized out>
2021-02-21 16:46:51 -          _a1 = <optimized out>
2021-02-21 16:46:51 -  #1  __pthread_cond_wait_common (abstime=0x7fffef122e40, mutex=0x555555a40518 <g_scheduler+24>, cond=0x555555a40540 <g_scheduler+64>) at pthread_cond_wait.c:539
2021-02-21 16:46:51 -          spin = 0
2021-02-21 16:46:51 -          buffer = {__routine = 0x7ffff61b3770 <__condvar_cleanup_waiting>, __arg = 0x7fffef122dc0, __canceltype = 1437033216, __prev = 0x0}
2021-02-21 16:46:51 -          cbuffer = {wseq = 103611746, cond = 0x555555a40540 <g_scheduler+64>, mutex = 0x555555a40518 <g_scheduler+24>, private = 0}
2021-02-21 16:46:51 -          err = <optimized out>
2021-02-21 16:46:51 -          g = 0
2021-02-21 16:46:51 -          flags = <optimized out>
2021-02-21 16:46:51 -          g1_start = <optimized out>
2021-02-21 16:46:51 -          maxspin = 0
2021-02-21 16:46:51 -          signals = <optimized out>
2021-02-21 16:46:51 -          result = 0
2021-02-21 16:46:51 -          wseq = <optimized out>
2021-02-21 16:46:51 -          seq = 51805873
2021-02-21 16:46:51 -          private = <optimized out>
2021-02-21 16:46:51 -          maxspin = <optimized out>
2021-02-21 16:46:51 -          err = <optimized out>
2021-02-21 16:46:51 -          result = <optimized out>
2021-02-21 16:46:51 -          wseq = <optimized out>
2021-02-21 16:46:51 -          g = <optimized out>
2021-02-21 16:46:51 -          seq = <optimized out>
2021-02-21 16:46:51 -          flags = <optimized out>
2021-02-21 16:46:51 -          private = <optimized out>
2021-02-21 16:46:51 -          signals = <optimized out>
2021-02-21 16:46:51 -          g1_start = <optimized out>
2021-02-21 16:46:51 -          spin = <optimized out>
2021-02-21 16:46:51 -          buffer = <optimized out>
2021-02-21 16:46:51 -          cbuffer = <optimized out>
2021-02-21 16:46:51 -          rt = <optimized out>
2021-02-21 16:46:51 -          s = <optimized out>
2021-02-21 16:46:51 -  #2  __pthread_cond_timedwait (cond=0x555555a40540 <g_scheduler+64>, mutex=0x555555a40518 <g_scheduler+24>, abstime=0x7fffef122e40) at pthread_cond_wait.c:667
2021-02-21 16:46:51 -  No locals.
2021-02-21 16:46:51 -  #3  0x000055555566f7d7 in Scheduler::threadMain() ()
2021-02-21 16:46:51 -  No symbol table info available.
2021-02-21 16:46:51 -  #4  0x00007ffff5a296df in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
2021-02-21 16:46:51 -  No symbol table info available.
2021-02-21 16:46:51 -  #5  0x00007ffff61ad6db in start_thread (arg=0x7fffef123700) at pthread_create.c:463
2021-02-21 16:46:51 -          pd = 0x7fffef123700
2021-02-21 16:46:51 -          now = <optimized out>
2021-02-21 16:46:51 -          unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737204336384, -2174702167556859638, 140737204334464, 0, 93824997617520, 140737488346160, 2174739178925873418, 2174688672002365706}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
2021-02-21 16:46:51 -          not_first_call = <optimized out>
2021-02-21 16:46:51 -  #6  0x00007ffff7b0371f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
2021-02-21 16:46:51 -  No locals.
2021-02-21 16:46:51 -  
2021-02-21 16:46:51 -  Thread 2 (Thread 0x7fffef924700 (LWP 28828)):
2021-02-21 16:46:51 -  #0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
2021-02-21 16:46:51 -  No locals.
2021-02-21 16:46:51 -  #1  0x00007ffff61b00f4 in __GI___pthread_mutex_lock (mutex=0x555556bcaec8) at ../nptl/pthread_mutex_lock.c:115
2021-02-21 16:46:51 -          ignore1 = <optimized out>
2021-02-21 16:46:51 -          ignore2 = <optimized out>
2021-02-21 16:46:51 -          ignore3 = <optimized out>
2021-02-21 16:46:51 -          id = 28828
2021-02-21 16:46:51 -          type = <optimized out>
2021-02-21 16:46:51 -          __PRETTY_FUNCTION__ = "__pthread_mutex_lock"
2021-02-21 16:46:51 -          id = <optimized out>
2021-02-21 16:46:51 -  #2  0x000055555573da32 in OutputMessagePool::sendAll() ()
2021-02-21 16:46:51 -  No symbol table info available.
2021-02-21 16:46:51 -  #3  0x00005555556afebf in Dispatcher::threadMain() ()
2021-02-21 16:46:51 -  No symbol table info available.
2021-02-21 16:46:51 -  #4  0x00007ffff5a296df in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
2021-02-21 16:46:51 -  No symbol table info available.
2021-02-21 16:46:51 -  #5  0x00007ffff61ad6db in start_thread (arg=0x7fffef924700) at pthread_create.c:463
2021-02-21 16:46:51 -          pd = 0x7fffef924700
2021-02-21 16:46:51 -          now = <optimized out>
2021-02-21 16:46:51 -          unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737212729088, -2174702167556859638, 140737212727168, 0, 93824997617120, 140737488346160, 2174738079951116554, 2174688672002365706}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
2021-02-21 16:46:51 -          not_first_call = <optimized out>
2021-02-21 16:46:51 -  #6  0x00007ffff7b0371f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
2021-02-21 16:46:51 -  No locals.
2021-02-21 16:46:51 -  
2021-02-21 16:46:51 -  Thread 1 (Thread 0x7ffff7fd3780 (LWP 28824)):
2021-02-21 16:46:51 -  #0  0x00005555556991b7 in Player::postRemoveNotification(Thing*, Cylinder const*, int, cylinderlink_t) ()
2021-02-21 16:46:51 -  No symbol table info available.
2021-02-21 16:46:51 -  #1  0x0000555555704c15 in Game::internalRemoveItem(Item*, int, bool, unsigned int) [clone .constprop.838] ()
2021-02-21 16:46:51 -  No symbol table info available.
2021-02-21 16:46:51 -  #2  0x00005555555815b4 in Player::stowContainer(Item*, unsigned int) ()
2021-02-21 16:46:51 -  No symbol table info available.
2021-02-21 16:46:51 -  #3  0x000055555558216d in ProtocolGame::parseStashWithdraw(NetworkMessage&) ()
2021-02-21 16:46:51 -  No symbol table info available.
2021-02-21 16:46:51 -  #4  0x0000555555646f57 in ProtocolGame::parsePacket(NetworkMessage&) ()
2021-02-21 16:46:51 -  No symbol table info available.
2021-02-21 16:46:51 -  #5  0x00005555556d36ca in Connection::parsePacket(boost::system::error_code const&) ()
2021-02-21 16:46:51 -  No symbol table info available.
2021-02-21 16:46:51 -  #6  0x00005555556dd486 in boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, std::_Bind<void (Connection::*(std::shared_ptr<Connection>, std::_Placeholder<1>))(boost::system::error_code const&)> > >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) ()
2021-02-21 16:46:51 -  No symbol table info available.
2021-02-21 16:46:51 -  #7  0x000055555559c465 in main ()
2021-02-21 16:46:51 -  No symbol table info available.

**Comment by marcosvf132** [comment]
Can you tell how this is happening so we can fix it? Also, there is another issue about this one so i will close this one and you can post a commentary there if you know anything that can help us to reproduce this error #2441
